##
## Makefile
##
## Made by vincent leroy
## Login   <leroy_v@epitech.eu>
##
## Started on  Tue Apr 02 12:23:55 2013 vincent leroy
## Last update Mon Apr 22 21:26:17 2013 fabien casters
##

EXECDIR = .
RESULT  = $(EXECDIR)/step1
SOURCES = Case.ml CaseMap.ml Affichage.ml main.ml
LIBS    = bigarray sdl sdlloader
INCDIRS = +sdl

include OCamlMakefile
