##
## Makefile
##
## Made by vincent leroy
## Login   <leroy_v@epitech.eu>
##
## Started on  Tue Apr 02 12:23:55 2013 vincent leroy
## Last update Mon Apr 29 17:19:00 2013 vincent leroy
##

EXECDIR = .
RESULT  = $(EXECDIR)/step2
SOURCES = Case.ml Affichage.ml main.ml
LIBS    = bigarray sdl sdlloader
INCDIRS = +sdl

include OCamlMakefile
